### ISSUE TITLE
Dear Zabrimus

### ISSUE THREAD

**Issue by frank-at** [Zabrimus/VDRSternELEC#77]
### To Reproduce
2. Play '....'
3. See error

### Informations
 - LE Version: [e.g. 9.2.1]
 - Hardware Platform: [e.g. RPi3]

**Comment by frank-at** [comment]
First of all thank you for your great work.
While creating images I ran into a problem with LibreELEC. While the CoreELEC image for my odroid-n2 works perfectly, the LibreELEC image for the RPi4 misses all configuration data for VDR. There is no directory /storage/.config/vdropt.
The binaries are available though in /usr/local/bin and /usr/local/lib.
I wonder whether it is possible/recommended to copy the subdirectories from the odroid-image.
Your comments will be much appreciated.
Michael

**Comment by Zabrimus** [comment]
Do you have called `/usr/local/bin/install.sh -i`. After the call all default configuration files in `/storage/.config/vdropt` should be available. See also https://github.com/Zabrimus/VDRSternELEC?tab=readme-ov-file#install-script

**Comment by frank-at** [comment]
Silly me! That did it, of course. As it did with the odroid-n2. As always: Read the manual!
Thank you very much.
Michael

**Comment by frank-at** [comment]
That's it.
