### ISSUE TITLE
[BUG] no Asset for latest "LibreELEC RPi RPi4" release but status is green

### ISSUE THREAD

**Issue by BstAA** [Zabrimus/VDRSternELEC#83]
### Describe the bug

For the "latest" i.e. 2024-06-01.1 release no RPi4 or RPi5 assets are generated, ... why?

**Comment by Zabrimus** [comment]
That's a good question. 
The build went fine, but the upload failed and logs are not available anymore. I just started a new build.

**Comment by Zabrimus** [comment]
Build finished all artifacts are uploaded.
